[package]
name = "Rusts-Basics"
version = "0.1.0"
edition = "2024"

[lib]
name = "rust_basics"
path = "src/lib.rs"

[[bin]]
name = "traits"
path = "src/bin/traits/bin.rs"

[dependencies]
tokio = { version = "1.41", features = ["full"] }
futures = "0.3"
async-trait = "0.1"
tokio-util = "0.7"
